language: node_js
node_js: stable
sudo: required
addons:
  apt:
    sources:
    - google-chrome
    packages:
    - google-chrome-stable
script:
- npm test
- if [ "${TRAVIS_PULL_REQUEST}" = "false" ]; then npm run test:sl; fi
env:
  global:
  - secure: WtpY7+XeOJnT6dTFUmpxXPLsH2+qk1XKAveF0XeR3lDfLjB1UJLLhPAZZPV/ZdRkhK9f/V/bkcMiY02Q5ifchFw/BOHg8dUj7zly21CrRfl1e0EDHgt/QfijVOdHDc/4e88MIoglhu5+A6HCJHirt+uZ8XhepXhea3jI9kNUeZn4I9QHGbzV12CwQeUPblYxfpf8ZBO/2p8zoemzjqkhutuEYrGwG/a8arusYmIu9wT5qiv+qiYzXV00EKwj5bLw9gwcs3dg6jewtITvdZ2hxk3yHAWfg0KgcSrxCG9hPOCR/w2yhLv9nVzcBkzFMjbRuHc9UEF/tWeT6cGYJ8ASBQK9XKMTXEJcIvVQtD5TQNiJnR8X4Dbsd7UuC3jJsysbKmCfPTOT8/pEfxbwJM3PHLd2YYTCv4Ucz3lUNPF7nIQrsJlK1a0O7EmOmHvKHJ/YpJt1lB0cz6Opt4LyiXRe+V6jwhcLbhiATiVLkyDmYcHB0OsNxgZIB5vCvM9mX6/n8BMLdssMxpe0H9VCSIWd39ittcw/RriNSNecn6ZBzu2MrONF6IemKB48Y87Embpbk9SpC8bgxTFsz07i4UpCedmHfp7nexba6r0ayaN3NhgPRDqSlli9QpWhEeusMnDvaAaQqX2zo9JFXoQVNchFwwXbRR4A5M5GHsjqOIVZ1u0=
  - secure: Gtb0vMBxHpsjG5WffRKpv/YiYpc7Lck8QlhdRlxTVUNg9Y7wO2pxNxbSas7P8pFbTIaSLgBBIQqC6zqs6oTrIhCNgOTcKw+aMJwHwfXvJBSkAt4wEw1oljHWS+pJ3yi6Dukk6oHtDNpS/UAQ7PzyBez5IjZxMW1ps3ns1TU6qarBvfIpf1bQd0XhgwDqEk0bH8GERH+mb+gXUEnzsTD4nVLPTFkOHN/5LriqfJhFlZejIwhb8c2hBmpFGhuEKDmDJAkAOHD8t99utEpRQSI4aun0tVdz+AlUwfMcfRY3Yiywa9+Cdq3btHYt4KCMthiZKcN6PCNa33XHJGVkFj8iYVddPi7xWsb7qRjuCizknAVLuKS0mizyqsyytLsMqo3CxiyW7fJfGG6q04krGn2m1oA7zVuc3cdu8FGTAw1HObNdzD6rq9XUjCJlktKFLh0qQgGBi3WCjMk4BOfwokuLBRMhpyoeuMTG5WiP8tOh/Mvr8PjE+Q7d3E+qXILV+5MJncij3gxLx9Y3UhVKavinBYsFACssbKqdZjckuGNIyVt2eQetD+tid09rT8Y05Btj9l+ShLqhpMmAeQVNu3sXHjiWpbdUrZCV3VZ0Uvnk1RiTd0qzM3m21uKdKPzSG0XrqW81y2XjuxJgNcBreiGE8/2KziPJVy2+lbiYPguovrU=
